spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/projeto_veterinario
    username: postgres
    password: 123456
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      dialect: org.hibernate.dialect.PostgreSQLDialect